// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8vx6te66sJfxakPHNbFl9bjVGH86BAz0',
    appId: '1:635015072636:web:e75419f172dc53901572f9',
    messagingSenderId: '635015072636',
    projectId: 'testing-10f26',
    authDomain: 'testing-10f26.firebaseapp.com',
    storageBucket: 'testing-10f26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZoP4cUuS46YOtRGUTxDSHWdG4Chm3e-0',
    appId: '1:635015072636:android:b052ad672fe2866c1572f9',
    messagingSenderId: '635015072636',
    projectId: 'testing-10f26',
    storageBucket: 'testing-10f26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSA31rpiupiMQM9WkplPNu3UeeLnJnfHQ',
    appId: '1:444741627342:ios:17e442b86227dba48d0f9f',
    messagingSenderId: '635015072636',
    projectId: 'testing-10f26',
    storageBucket: 'testing-10f26.appspot.com',
    iosClientId: '635015072636-94oj4bnb8cl4v04odr9ndes303jn01i6.apps.googleusercontent.com',
    iosBundleId: 'com.nutrihub',
  );
}
